
server:
  port: 9002
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/redisdemo
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    
  redis:
    port: 6379
    host: localhost
  cache:
    redis:
      cache-null-values: false
      time-to-live: 60000  
  main:
    allow-bean-definition-overriding: true  
    
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect 